name: Build and Deploy Main API

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Build Docker image
      run: make docker-build-base

    - name: Push Docker image
      run: make docker-push-base
